#include <stdio.h>
#include <stdlib.h>

#define LINE_MAX 2048
#define MAX_SYMBOLS 256



/* Structure to hold information about the file being compressed */
typedef struct CompressInfo{
    FILE * file; //Pointer to the file that is being compressed
    char * file_path; //Stores the file path 
    int is_open_file; //Informs if the file is currently open and needs to be closed
    int total_symbols; //Number of total symbols in the file
    int n_symbols; //Number of unique symbols in the file
    char * symbols; //Array of symbols in the file
    float * probabilities; //Array of probabilities of each symbol that resides in the file
    unsigned long long * new_symbols; //Array of new bit sequences that represent the symbols in the file
    int * code_len; //Array of the code length for each new symbol generated by the algorithm
    int number_zeros; //Tells the number of '\0' characters in the file for safe decompression
}CompressInfo;


typedef struct BitWriter{
    FILE * file;
    unsigned char buffer;
    int flush_bits;
}BitWriter;